---
language: "php"
services:
  - "mysql"
php:
  - "7.2"
before_install:
  - "mysql -e 'create database inroads'"
  - "mysql inroads < scripts/mysql.sql"
install:
  - "composer install"
before_script:
    - "cp tests/UnitTests/site_config.inc.default data/site_config.inc"
script: "phpunit -c phpunit.xml"
...
