<head>
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URI; ?>/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URI; ?>/css/layouts/<?php echo $this->layout; ?>.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo BASE_URI; ?>/css/screen.css" />
	<title><?php echo isset($this->title) ? self::escape($this->title) : APPLICATION_NAME; ?></title>
</head>
