---
- hosts: "inroads"
  become: "yes"
  roles:
    - "City-of-Bloomington.mysql"
    - "City-of-Bloomington.php"

  tasks:
    - name: "Install distro packages for inRoads"
      apt:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "php-mysql"

    - name: "Create mysql database"
      mysql_db:
        config_file: "{{ mysql_defaults_extra_file }}"
        name: "{{ inroads_db.name }}"
        state: present
      no_log: True

    - name: "Create mysql user for site"
      mysql_user:
        name:     "{{ inroads_db.user }}"
        password: "{{ inroads_db.pass }}"
        priv:     "{{ inroads_db.name }}.*:ALL"
        state: present
        config_file: "{{ mysql_defaults_extra_file }}"
      no_log: True

    - name: "Extract release"
      unarchive:
        src: "{{ inroads_archive_path }}"
        dest: "/usr/local/src"
      register: release

    - name: "Remove old release"
      file:
        path: "{{ inroads_install_path }}"
        state: "absent"
      when: release.changed

    - name: "Create InRoads directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode: u=rwx,g=rwxs,o=rx
      with_items:
        - "{{ inroads_install_path }}"
        - "{{ inroads_backup_path  }}"
        - "{{ inroads_site_home    }}"
        - "/var/log/cron"

    - name: "Install release"
      command: "rsync -rlv /usr/local/src/inroads/ {{ inroads_install_path }}/"
      when: release.changed

    - name: "Update site_home"
      command: "rsync -rl /usr/local/src/inroads/data/ {{ inroads_site_home }}/"
      when: release.changed

    - name: "Update site_config"
      template:
        src: "site_config.j2"
        dest: "{{ inroads_site_home }}/site_config.inc"

    - name: "Apache site configuration"
      template:
        src: "inroads.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/inroads.conf"
      notify: "apache_restart"

    - name: "Install Backup CRON"
      template:
        src: "backup.sh"
        dest: "/etc/cron.daily/backup.d/inroads"
        mode: "0755"

    - name: "Configure backup credentials"
      template:
        src: "backup.cnf"
        dest: "/etc/cron.daily/backup.d/inroads.cnf"
        mode: "0600"

    - name: "Install Weekly CRON"
      template:
        src: "weekly.sh"
        dest: "/etc/cron.d/inroads"
        mode: "0755"

    - name: "Update application permissions"
      file:
        path:  "{{ inroads_install_path }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwX,o=rX"
        recurse: "yes"

    - name: "Update site_home permissions"
      file:
        path: "{{ inroads_site_home }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwX,o=rX"
        recurse: "yes"
...
